# Generated by Django 3.0.7 on 2020-06-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_action_id', models.CharField(blank=True, help_text='The ID of the action in an external system', max_length=50, null=True)),
                ('call_datetime', models.DateTimeField(help_text='What time did you receive the call about this action?', null=True)),
                ('call_duration', models.DurationField(blank=True, help_text='How long was the call?', null=True)),
                ('requested_datetime', models.DateTimeField(help_text='When should the action be completed by?', null=True, verbose_name='Due')),
                ('action_status', models.CharField(choices=[('1', 'Pending volunteer interest'), ('2', 'Volunteer interest'), ('3', 'Volunteer assigned'), ('4', 'Ongoing'), ('5', 'Completed'), ('6', "Couldn't complete"), ('7', 'No longer needed')], default='1', help_text="What's the status of this action?", max_length=1)),
                ('action_priority', models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='2', help_text='What priority should this action be given?', max_length=1)),
                ('public_description', models.TextField(blank=True, help_text='Text that gets displayed to volunteers who are browsing actions.', max_length=500, null=True)),
                ('private_description', models.TextField(blank=True, help_text="Text that only gets displayed to a volunteer when they're assigned to the action.", null=True)),
                ('volunteer_made_contact_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name='Assigned on')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed on')),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('added_by', models.ForeignKey(help_text="What's your name?", on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to='users.Coordinator')),
                ('assigned_volunteer', models.ForeignKey(blank=True, help_text='The volunteer who will complete the action.', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer')),
                ('coordinator', models.ForeignKey(help_text='Who will mediate this action?', on_delete=django.db.models.deletion.PROTECT, related_name='coordinator', to='users.Coordinator')),
                ('help_type', models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.HelpType', verbose_name='Action type')),
                ('interested_volunteers', models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_interested_in', to='users.Volunteer')),
                ('requirements', models.ManyToManyField(blank=True, help_text='Only volunteers matching these requirements will see the action.', related_name='actions', to='categories.Requirement')),
                ('resident', models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='ActionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DurationField(blank=True, help_text='How long did it take to complete the action?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes from the volunteer', max_length=500, null=True)),
                ('created_date_time', models.DateTimeField(blank=True, help_text='This field is updated automatically.', null=True)),
                ('action', models.ForeignKey(help_text='The feedback subject', on_delete=django.db.models.deletion.PROTECT, to='actions.Action')),
                ('volunteer', models.ForeignKey(help_text='Who wrote the feedback', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
