# Generated by Django 3.0.5 on 2020-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_datetime', models.DateTimeField(help_text='What time did you receive the call about this action?', null=True)),
                ('call_duration', models.DurationField(blank=True, help_text='How long was the call?', null=True)),
                ('requested_datetime', models.DateTimeField(help_text='When should the action be completed by?', null=True)),
                ('action_status', models.CharField(choices=[('1', 'Pending volunteer interest'), ('2', 'Volunteer interest'), ('3', 'Volunteer assigned'), ('4', 'Completed'), ('5', "Couldn't complete")], default='1', help_text="What's the status of this action?", max_length=1)),
                ('action_priority', models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='1', help_text='What priority should this action be given?', max_length=1)),
                ('time_taken', models.DurationField(blank=True, help_text='How long did it take to complete the action?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes from the volunteer.', max_length=500, null=True)),
                ('public_description', models.TextField(blank=True, help_text='Text that gets displayed to volunteers who are browsing actions.', max_length=500, null=True)),
                ('private_description', models.TextField(blank=True, help_text="Text that only gets displayed to a volunteer when they're assigned to the action.", null=True)),
            ],
        ),
    ]
