# Generated by Django 3.0.7 on 2020-11-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_seed'),
        ('users', '0003_auto_20201122_2050'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_action_id', models.CharField(blank=True, help_text='The ID of the action in an external system', max_length=50, null=True)),
                ('requested_datetime', models.DateTimeField(help_text='When should the action be completed by?', null=True, verbose_name='Due')),
                ('num_volunteers_needed', models.IntegerField()),
                ('action_status', models.CharField(choices=[('pending', 'Pending volunteer interest'), ('interest', 'Volunteer interest'), ('assigned', 'Volunteer assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('couldnt_complete', "Couldn't complete"), ('no_longer_needed', 'No longer needed')], default='pending', help_text="What's the status of this action?", max_length=30)),
                ('action_priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', help_text='What priority should this action be given?', max_length=30)),
                ('public_description', models.TextField(blank=True, help_text='Text that gets displayed to volunteers who are browsing actions.', max_length=500, null=True)),
                ('private_description', models.TextField(blank=True, help_text="Text that only gets displayed to a volunteer when they're assigned to the action.", null=True)),
                ('allow_auto_assign', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionVolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback_notes', models.TextField(blank=True, max_length=999, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('repetition_requested', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.ActionV2')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='actionv2',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_assigned2', through='actions.ActionVolunteerAssignment', to='users.Volunteer'),
        ),
        migrations.AddField(
            model_name='actionv2',
            name='help_type',
            field=models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.HelpType', verbose_name='Action type'),
        ),
        migrations.AddField(
            model_name='actionv2',
            name='interested_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_interested_in2', to='users.Volunteer'),
        ),
        migrations.AddField(
            model_name='actionv2',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Only volunteers matching these requirements will see the action.', related_name='actions2', to='categories.Requirement'),
        ),
        migrations.AddField(
            model_name='actionv2',
            name='resident',
            field=models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Resident'),
        ),
    ]
