# Generated by Django 3.0.7 on 2020-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20201122_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionvolunteerassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('feedback_given', 'Feedback given')], default='assigned', max_length=30),
        ),
    ]
