# Generated by Django 3.0.5 on 2020-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_seed_requirement'),
        ('actions', '0003_action_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Only volunteers matching these requirements will see the action.', related_name='actions', to='categories.Requirement'),
        ),
    ]
