# Generated by Django 3.0.7 on 2020-11-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_actionvolunteerassignment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionv2',
            old_name='requested_datetime',
            new_name='due_datetime',
        ),
    ]
