# Generated by Django 3.0.7 on 2021-03-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210316_2035'),
        ('actions', '0004_remove_action_uuid_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionVolunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='volunteers',
            field=models.ManyToManyField(related_name='action_volunteers', through='actions.ActionVolunteers', to='users.Volunteer'),
        ),
    ]
