# Generated by Django 3.0.7 on 2021-03-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210316_2035'),
        ('actions', '0004_remove_action_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='maximum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='maximum number of volunteers required for action'),
        ),
        migrations.AddField(
            model_name='action',
            name='minimum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='minimum number of volunteers required for action'),
        ),
        migrations.CreateModel(
            name='ActionAssignedVolunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(help_text='Assigned Action', on_delete=django.db.models.deletion.PROTECT, to='actions.Action')),
                ('assigned_volunteer', models.ForeignKey(help_text='Assigned Volunteer', on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have been assigned to completing the action..', related_name='actions_assigned_to', through='actions.ActionAssignedVolunteers', to='users.Volunteer'),
        ),
    ]
