# Generated by Django 3.0.7 on 2020-11-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201122_2050'),
        ('actions', '0004_auto_20201122_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending volunteer interest'), ('interest', 'Volunteer interest'), ('assigned', 'Volunteer assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('couldnt_complete', "Couldn't complete"), ('no_longer_needed', 'No longer needed')], default='pending', help_text="What's the status of this action-occurrence?", max_length=30)),
                ('due_datetime', models.DateTimeField(help_text='When should the action-occurrence be completed by?', verbose_name='Due')),
                ('min_volunteers', models.IntegerField(default=1)),
                ('max_volunteers', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ActionOccurrenceVolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('contact_made', 'Contact made'), ('feedback_given', 'Feedback given')], default='assigned', max_length=30)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('volunteer_made_contact_on', models.DateTimeField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True, max_length=999, null=True)),
                ('repetition_requested', models.BooleanField(default=False)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('action_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.ActionOccurrence')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer')),
            ],
            options={
                'unique_together': {('action_occurrence', 'volunteer')},
            },
        ),
        migrations.RemoveField(
            model_name='actionv2',
            name='action_status',
        ),
        migrations.RemoveField(
            model_name='actionv2',
            name='assigned_volunteers',
        ),
        migrations.RemoveField(
            model_name='actionv2',
            name='due_datetime',
        ),
        migrations.RemoveField(
            model_name='actionv2',
            name='interested_volunteers',
        ),
        migrations.RemoveField(
            model_name='actionv2',
            name='num_volunteers_needed',
        ),
        migrations.AddField(
            model_name='actionv2',
            name='max_volunteers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='actionv2',
            name='min_volunteers',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ActionVolunteerAssignment',
        ),
        migrations.AddField(
            model_name='actionoccurrence',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.ActionV2'),
        ),
        migrations.AddField(
            model_name='actionoccurrence',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_assigned2', through='actions.ActionOccurrenceVolunteerAssignment', to='users.Volunteer'),
        ),
        migrations.AddField(
            model_name='actionoccurrence',
            name='interested_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_interested_in2', to='users.Volunteer'),
        ),
    ]
