# Generated by Django 3.0.5 on 2020-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20200514_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_priority',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='2', help_text='What priority should this action be given?', max_length=1),
        ),
    ]
