# Generated by Django 3.0.7 on 2021-03-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20210318_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionfeedback',
            name='action_volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='actions.ActionVolunteers'),
        ),
    ]
