# Generated by Django 3.0.7 on 2021-04-11 09:32

from django.db import migrations
from actions.utils import copy_volunteers

def forwards(apps, schema_editor):
    copy_volunteers()

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20210411_0932'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
