# Generated by Django 3.0.5 on 2020-05-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_1434'),
        ('actions', '0005_auto_20200514_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='action',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, help_text='The volunteer who will complete the action.', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer'),
        ),
        migrations.AddField(
            model_name='action',
            name='interested_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='interested_volunteers', to='users.Volunteer'),
        ),
    ]
