# Generated by Django 3.0.5 on 2020-05-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20200521_1537'),
        ('actions', '0006_auto_20200521_1137'),
    ]

    operations = [
    ]
