# Generated by Django 3.0.7 on 2021-03-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210316_2035'),
        ('actions', '0006_actionfeedback_action_volunteer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionvolunteers',
            unique_together={('action', 'volunteer')},
        ),
    ]
