# Generated by Django 3.0.7 on 2021-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actionfeedback_assigned_volunteer_action'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actionassignedvolunteers',
            constraint=models.UniqueConstraint(fields=('action', 'assigned_volunteer'), name='unique assigned action volunteer'),
        ),
    ]
