# Generated by Django 3.0.5 on 2020-05-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20200521_1537'),
        ('actions', '0007_merge_20200525_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='help_type',
            field=models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.HelpType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='requested_datetime',
            field=models.DateTimeField(help_text='When should the action be completed by?', null=True),
        ),
    ]
