# Generated by Django 3.0.5 on 2020-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_add_ongoing_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_status',
            field=models.CharField(choices=[('1', 'Pending volunteer interest'), ('2', 'Volunteer interest'), ('3', 'Volunteer assigned'), ('4', 'Ongoing'), ('5', 'Completed'), ('6', "Couldn't complete")], default='1', help_text="What's the status of this action?", max_length=1),
        ),
    ]
