# Generated by Django 3.0.7 on 2021-05-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210316_2035'),
        ('actions', '0007_auto_20210512_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='resident',
            field=models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_actions', to='users.Resident'),
        ),
    ]
