# Generated by Django 3.0.7 on 2021-03-18 23:14

from django.db import migrations

from actions.utils import copy_volunteers, copy_feedback

def forwards(apps, schema_editor):
    copy_volunteers()
    copy_feedback()

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20210318_2313'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
