# Generated by Django 3.0.7 on 2021-05-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210316_2035'),
        ('actions', '0008_auto_20210512_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of  organisation.', max_length=100)),
                ('address_line_1', models.CharField(help_text='First line of their address.', max_length=100)),
                ('address_line_2', models.CharField(blank=True, help_text='Second line of their address.', max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, help_text='Third line of their address.', max_length=100, null=True)),
                ('postcode', models.CharField(help_text='Address postcode.', max_length=10)),
                ('email', models.CharField(blank=True, help_text='Main email for organisation contact.', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any other notes?', null=True)),
                ('contact_name', models.CharField(help_text='Name of  organisation contact.', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Main phone number for organisation contact.', max_length=20, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_referal_id', models.CharField(blank=True, help_text='The ID of the referral in an external system', max_length=50, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed on')),
                ('notes', models.TextField(blank=True, help_text='Notes describing referral', null=True)),
                ('added_by', models.ForeignKey(help_text="What's your name?", on_delete=django.db.models.deletion.PROTECT, related_name='referral_added_by', to='users.Coordinator')),
                ('coordinator', models.ForeignKey(help_text='Who will mediate this referral?', on_delete=django.db.models.deletion.PROTECT, related_name='referral_coordinator', to='users.Coordinator')),
                ('resident', models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_referrals', to='users.Resident')),
            ],
        ),
    ]
