# Generated by Django 3.0.5 on 2020-05-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20200525_0932'),
        ('actions', '0008_auto_20200522_0950'),
    ]

    operations = [
    ]
