# Generated by Django 3.0.5 on 2020-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20200522_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='volunteer_made_contact_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
