# Generated by Django 3.0.7 on 2021-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20210318_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='maximum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='maximum number of volunteers required for action'),
        ),
        migrations.AddField(
            model_name='action',
            name='minimum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='minimum number of volunteers required for action'),
        ),
    ]
