# Generated by Django 3.0.5 on 2020-05-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_merge_20200526_0759'),
        ('actions', '0009_action_volunteer_made_contact_on'),
    ]

    operations = [
    ]
