# Generated by Django 3.0.7 on 2021-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_auto_20210323_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionfeedback',
            name='assigned_volunteer_action',
            field=models.ForeignKey(help_text='Which assigned volunteer action?', null=True, on_delete=django.db.models.deletion.PROTECT, to='actions.ActionAssignedVolunteers'),
        ),
    ]
