# Generated by Django 3.0.7 on 2021-05-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20210519_1434'),
        ('actions', '0009_organisation_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.ForeignKey(help_text='Which kind of referral is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.ReferralType'),
        ),
    ]
