# Generated by Django 3.0.7 on 2021-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_referral_referral_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_status',
            field=models.CharField(choices=[('1', 'Coordinator has chosen a referral organisation, but still needs to contact them'), ('2', 'Referral organisation contacted'), ('3', 'Referral to organisation complete')], default='1', help_text="What's the status of this action?", max_length=1),
        ),
    ]
