# Generated by Django 3.0.7 on 2021-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_referral_referral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Name of  organisation contact.', max_length=100, null=True),
        ),
    ]
