# Generated by Django 3.0.5 on 2020-05-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20200526_2051'),
        ('actions', '0011_auto_20200526_1915'),
    ]

    operations = [
    ]
