# Generated by Django 3.0.7 on 2021-05-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_auto_20210526_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_organisation',
            field=models.ForeignKey(help_text='What organisation are you referring to?', null=True, on_delete=django.db.models.deletion.PROTECT, to='actions.Organisation'),
        ),
    ]
