# Generated by Django 3.0.5 on 2020-05-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_1434'),
        ('actions', '0012_merge_20200527_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='interested_volunteers',
            field=models.ManyToManyField(blank=True, help_text='Volunteers who have expressed interest in completing the action..', related_name='actions_interested_in', to='users.Volunteer'),
        ),
    ]
