# Generated by Django 3.0.5 on 2020-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20200528_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='assigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Assigned on'),
        ),
        migrations.AddField(
            model_name='action',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completed on'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_status',
            field=models.CharField(choices=[('1', 'Pending volunteer interest'), ('2', 'Volunteer interest'), ('3', 'Volunteer assigned'), ('4', 'Ongoing'), ('5', 'Completed'), ('6', "Couldn't complete"), ('7', 'No longer needed')], default='1', help_text="What's the status of this action?", max_length=1),
        ),
    ]
