# Generated by Django 3.0.5 on 2020-05-28 21:33

from actions.models import ActionFeedback
from django.db import migrations, models
from datetime import datetime


def create_action_feedback_models(apps, schema_editor):
    Action = apps.get_model("actions", "Action")
    for action in Action.objects.all():
        af = ActionFeedback(
            action=action,
            notes=action.notes,
            time_taken=action.time_taken,
            created_date_time=datetime.utcnow())
        af.save()

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20200528_2133'),
    ]

    operations = [
        migrations.RunPython(create_action_feedback_models),
        migrations.RemoveField(
            model_name='action',
            name='time_taken'
        ),
        migrations.RemoveField(
            model_name='action',
            name='notes'
        ),
    ]
