# Generated by Django 3.0.7 on 2020-06-16 13:00

from django.db import migrations, models
from datetime import datetime


def create_action_feedback_models(apps, schema_editor):
    ActionFeedback = apps.get_model("actions", "ActionFeedback")
    Action = apps.get_model("actions", "Action")
    for action in Action.objects.all():
        af = ActionFeedback(
            action=action,
            notes=action.notes,
            time_taken=action.time_taken,
            created_date_time=datetime.utcnow())
        af.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20200528_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(help_text='The feedback subject', null=False, on_delete=models.deletion.PROTECT, to='actions.Action')),
                ('time_taken', models.DurationField(blank=True, help_text='How long did it take to complete the action?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes from the volunteer.', max_length=500, null=True)),
                ('created_date_time', models.DateTimeField(help_text='This field is updated automatically.', null=True))
            ],
        ),
        migrations.RunPython(create_action_feedback_models),
        migrations.RemoveField(
            model_name='action',
            name='time_taken'
        ),
        migrations.RemoveField(
            model_name='action',
            name='notes'
        ),
    ]
