# Generated by Django 3.0.5 on 2020-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20200618_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned on'),
        ),
        migrations.AlterField(
            model_name='action',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed on'),
        ),
    ]
