# Generated by Django 3.0.7 on 2021-07-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20210527_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_organisation',
            field=models.ForeignKey(help_text='What organisation are you referring to?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_referrals', to='actions.Organisation'),
        ),
    ]
