# Generated by Django 3.0.7 on 2020-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20200616_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionfeedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterField(
            model_name='actionfeedback',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from the volunteer', max_length=500, null=True),
        ),
    ]
