# Generated by Django 3.0.7 on 2021-07-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_auto_20210529_1142'),
        ('actions', '0015_auto_20210718_2241'),
    ]

    operations = [
    ]
