# Generated by Django 3.0.7 on 2020-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_auto_20200619_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionfeedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='actionfeedback',
            name='created_date_time',
            field=models.DateTimeField(blank=True, help_text='This field is updated automatically.', null=True),
        ),
    ]
