# Generated by Django 3.0.7 on 2020-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_auto_20200619_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionfeedback',
            name='volunteer',
            field=models.ForeignKey(help_text="Who wrote the feedback", null=True, on_delete=models.deletion.PROTECT, to='users.Volunteer'),
        ),
    ]
