# Generated by Django 3.0.7 on 2020-06-22 16:40

from django.db import migrations, models


def assign_feeback_volunteers(apps, schema_editor):
    ActionFeedback = apps.get_model("actions", "ActionFeedback")
    for af in ActionFeedback.objects.all():
        af.volunteer = af.action.assigned_volunteer
        af.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_auto_20200622_1638'),
    ]

    operations = [
        migrations.RunPython(assign_feeback_volunteers),
    ]
