# Generated by Django 3.0.7 on 2020-06-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_auto_20200622_1640'),
        ('actions', '0015_auto_20200618_1206'),
    ]

    operations = [
    ]
