# Generated by Django 3.0.7 on 2020-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_merge_20200622_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='external_action_id',
            field=models.CharField(blank=True, help_text='The ID of the action in an external system', max_length=50, null=True),
        ),
    ]
