# Generated by Django 3.0.5 on 2020-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_action_external_action_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
