# Generated by Django 3.0.5 on 2020-05-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('private_description_template', models.TextField(blank=True, help_text='Private description will be pre-filled with this text when picking this type of help for a Action', null=True)),
                ('public_description_template', models.TextField(blank=True, help_text='Public description will be pre-filled with this text when picking this type of help for a Action', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
