# Generated by Django 3.0.5 on 2020-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptype',
            name='icon_name',
            field=models.CharField(
                help_text="Name of the fontawesome icon used to represent this type of help (among the 'free' ones: https://fontawesome.com/icons?d=gallery&m=free)", max_length=50, null=True),
        ),
    ]
