# Generated by Django 3.0.5 on 2020-05-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200512_1434'),
        ('actions', '0005_auto_20200514_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('PENDING_HIGH_PRIORITY', 'High priority action is pending'), ('VOLUNTEER_INTEREST', 'Volunteed manifested interest'), ('VOLUNTEER_ASSIGNED', 'Volunteer was assigned'), ('ACTION_COMPLETED', 'Volunteer completed the action'), ('ACTION_NOT_COMPLETED', 'Volunteer could not complete the action')], editable=False, max_length=100, null=True)),
                ('subject', models.CharField(help_text='The notification subject.', max_length=100, null=True)),
                ('message', models.TextField(help_text="What's your name?", max_length=1000, null=True)),
                ('delivered', models.BooleanField(default=False, help_text='This field is updated automatically.')),
                ('sent_by', models.CharField(help_text="Who's sending the notification?", max_length=50)),
                ('created_date_time', models.DateTimeField(help_text='This field is updated automatically.', null=True)),
                ('delivered_date_time', models.DateTimeField(help_text='This field is updated automatically.', null=True)),
                ('action', models.ForeignKey(help_text='The action the notification is about.', null=True, on_delete=django.db.models.deletion.PROTECT, to='actions.Action')),
                ('recipients', models.ManyToManyField(default=list, help_text='This field is updated automatically.', related_name='notificationrecipient', to='users.Person')),
            ],
        ),
    ]
