# Generated by Django 3.0.5 on 2020-05-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_by',
        ),
    ]
