# Generated by Django 3.0.5 on 2020-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('PENDING_HIGH_PRIORITY', 'High priority action is pending'), ('VOLUNTEER_INTEREST', 'Volunteed manifested interest'), ('VOLUNTEER_ASSIGNED', 'Volunteer was assigned'), ('VOLUNTEER_NOT_ASSIGNED', 'Volunteer was not assigned'), ('ACTION_COMPLETED', 'Volunteer completed the action'), ('ACTION_NOT_COMPLETED', 'Volunteer could not complete the action')], editable=False, max_length=100, null=True),
        ),
    ]
