# Generated by Django 3.0.5 on 2020-06-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200623_0824'),
        ('notifications', '0004_auto_20200623_1055'),
    ]

    operations = [
    ]
