# Generated by Django 3.0.7 on 2020-06-23 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200623_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Email addresses of recipients.', null=True, size=None),
        ),
    ]
