# Generated by Django 3.0.5 on 2020-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_merge_20200623_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('PENDING_HIGH_PRIORITY', 'High priority action is pending'), ('VOLUNTEER_INTEREST', 'Volunteed manifested interest'), ('VOLUNTEER_ASSIGNED', 'Volunteer was assigned'), ('VOLUNTEER_NOT_ASSIGNED', 'Volunteer was not assigned'), ('VOLUNTEER_CONTACT', 'Volunteer made contact with the resident'), ('ACTION_COMPLETED', 'Volunteer completed the action'), ('ACTION_NOT_COMPLETED', 'Volunteer could not complete the action'), ('ACTION_ONGOING', 'Volunteer marked action as ongoing')], editable=False, max_length=100, null=True),
        ),
    ]
