# Generated by Django 3.0.5 on 2020-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20200624_0925'),
        ('notifications', '0007_auto_20200625_1124'),
    ]

    operations = [
    ]
