# Generated by Django 3.0.7 on 2020-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20200623_1212'),
        ('notifications', '0007_auto_20200624_0925'),
    ]

    operations = [
    ]
