version: '3'
services:

  # PostgreSQL database, with GIS extension.
  db:
    build:
      context: ./db/
    container_name: tofro-db
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_BCC_USER=${POSTGRES_BCC_USER}
      - POSTGRES_BCC_PASSWORD=${POSTGRES_BCC_PASSWORD}
    volumes:
      - data_volume:/var/lib/postgresql/data

  # Django Python Backend.
  server:
    build:
      context: ./api/
    container_name: tofro-django
    restart: unless-stopped
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}

      - DJANGO_PORT=${DJANGO_PORT}
      - DJANGO_ADMIN_FIRSTNAME=${DJANGO_ADMIN_FIRSTNAME}
      - DJANGO_ADMIN_LASTNAME=${DJANGO_ADMIN_LASTNAME}
      - DJANGO_ADMIN_PASSWORD=${DJANGO_ADMIN_PASSWORD}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

      - ADMIN_SITE_TITLE=${ADMIN_SITE_TITLE}
      - SITE_URL=${SITE_URL}

      - DEBUG=${DEBUG}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

      # Used in production deployment with Ansible.
      - DJANGO_HTTPS=${DJANGO_HTTPS}
      - HOSTNAME=${HOSTNAME}

volumes:
  data_volume:
