version: '3'
services:

  # PostgreSQL database, with GIS extension.
  db:
    image: mdillon/postgis
    container_name: tofro-db
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data_volume:/var/lib/postgresql/data

  # Django Python Backend.
  server:
    build:
      context: ./
    env_file:
      - ./.env
      - ./.email.env
    container_name: tofro-django
    restart: unless-stopped
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - "./:/code"

volumes:
  data_volume:
