# Generated by Django 3.0.5 on 2020-05-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(default=[], help_text='This field is updated automatically.', related_name='notificationrecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(help_text="What's your name?", on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to='users.Coordinator'),
        ),
        migrations.AddField(
            model_name='job',
            name='coordinator',
            field=models.ForeignKey(help_text='Who will mediate this task?', on_delete=django.db.models.deletion.PROTECT, related_name='coordinator', to='users.Coordinator'),
        ),
        migrations.AddField(
            model_name='job',
            name='help_type',
            field=models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.HelpType'),
        ),
        migrations.AddField(
            model_name='job',
            name='requester',
            field=models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Requester'),
        ),
        migrations.AddField(
            model_name='job',
            name='volunteer',
            field=models.ForeignKey(blank=True, help_text='Who will complete the task?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer'),
        ),
    ]
