# Generated by Django 3.0.5 on 2020-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_data_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_primary',
            field=models.CharField(help_text='Main email for the user.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_secondary',
            field=models.CharField(help_text='Secondary email for the user.', max_length=50, null=True),
        ),
    ]
