# Generated by Django 3.0.5 on 2020-04-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_increase_email_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='available_fri_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_fri_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_fri_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_morning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_afternoon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_evening',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_morning',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
