# Generated by Django 3.0.5 on 2020-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200426_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='help_type',
            field=models.ManyToManyField(to='core.HelpType'),
        ),
    ]
