# Generated by Django 3.0.5 on 2020-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_help_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='private_description',
            field=models.TextField(blank=True, help_text="Text that'll only get displayed to the helpers after they did the job", null=True),
        ),
    ]
