# Generated by Django 3.0.5 on 2020-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_private_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(help_text='Any other notes?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='public_description',
            field=models.TextField(help_text='Text that gets displayed to helpers.', max_length=500, null=True),
        ),
    ]
