# Generated by Django 3.0.5 on 2020-04-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200426_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='help_type',
        ),
        migrations.AddField(
            model_name='job',
            name='help_type',
            field=models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.HelpType'),
        ),
    ]
