# Generated by Django 3.0.5 on 2020-04-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200426_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='helper',
            field=models.ForeignKey(blank=True, help_text='Who will help?', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Helper'),
        ),
    ]
