# Generated by Django 3.0.5 on 2020-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_helper_wards'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='help_types',
            field=models.ManyToManyField(related_name='helpers', to='core.HelpType'),
        ),
    ]
