# Generated by Django 3.0.5 on 2020-04-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_helper_help_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='dbs_number',
            field=models.CharField(blank=True, help_text="The user's DBS certificate number, if they have one.", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='reference_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='call_duration',
            field=models.DurationField(blank=True, help_text='How long was the call?', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, help_text='Any other notes?', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The notification subject.', max_length=100, null=True)),
                ('message', models.TextField(help_text="What's your name?", max_length=1000, null=True)),
                ('delivered', models.BooleanField(default=False, help_text='This field is updated automatically.')),
                ('sent_by', models.CharField(help_text="Who's sending the notification?", max_length=50)),
                ('user_query', models.CharField(blank=True, help_text='The user selection query. Syntax TBC.', max_length=250, null=True)),
                ('created_date_time', models.DateTimeField(help_text='This field is updated automatically.', null=True)),
                ('delivered_date_time', models.DateTimeField(help_text='This field is updated automatically.', null=True)),
                ('job', models.ForeignKey(help_text='The job the notification is about.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Job')),
                ('recipients', models.ManyToManyField(default=[], help_text='This field is updated automatically.', related_name='notificationrecipient', to='core.User')),
            ],
        ),
    ]
