# Generated by Django 3.0.5 on 2020-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_helper_help_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpriority',
            options={'verbose_name_plural': 'Job priorities'},
        ),
        migrations.AlterField(
            model_name='helper',
            name='access_to_car',
            field=models.BooleanField(default=False, verbose_name='Has access to a car'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_fri_afternoon',
            field=models.BooleanField(default=False, verbose_name='Friday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_fri_evening',
            field=models.BooleanField(default=False, verbose_name='Friday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_fri_morning',
            field=models.BooleanField(default=False, verbose_name='Friday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_afternoon',
            field=models.BooleanField(default=False, verbose_name='Monday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_evening',
            field=models.BooleanField(default=False, verbose_name='Monday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_mon_morning',
            field=models.BooleanField(default=False, verbose_name='Monday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_afternoon',
            field=models.BooleanField(default=False, verbose_name='Saturday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_evening',
            field=models.BooleanField(default=False, verbose_name='Saturday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sat_morning',
            field=models.BooleanField(default=False, verbose_name='Staturday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_afternoon',
            field=models.BooleanField(default=False, verbose_name='Sunday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_evening',
            field=models.BooleanField(default=False, verbose_name='Sunday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_sun_morning',
            field=models.BooleanField(default=False, verbose_name='Sunday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_afternoon',
            field=models.BooleanField(default=False, verbose_name='Thursday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_evening',
            field=models.BooleanField(default=False, verbose_name='Thursday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_thur_morning',
            field=models.BooleanField(default=False, verbose_name='Thursday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_afternoon',
            field=models.BooleanField(default=False, verbose_name='Tuesday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_evening',
            field=models.BooleanField(default=False, verbose_name='Tuesday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_tues_morning',
            field=models.BooleanField(default=False, verbose_name='Tuesday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_afternoon',
            field=models.BooleanField(default=False, verbose_name='Wednesday afternoon'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_evening',
            field=models.BooleanField(default=False, verbose_name='Wednesday evening'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='available_wed_morning',
            field=models.BooleanField(default=False, verbose_name='Wednesday morning'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='dbs_number',
            field=models.CharField(blank=True, help_text="The user's DBS certificate number, if they have one.", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='driving_license',
            field=models.BooleanField(default=False, verbose_name='Has a driving license'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='health_checklist_received',
            field=models.BooleanField(default=False, verbose_name='Has received their health checklist'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='id_received',
            field=models.BooleanField(default=False, verbose_name='Has sent a copy of their ID'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='key_worker',
            field=models.BooleanField(default=False, verbose_name='Has received key worker letter from council'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='ts_and_cs_confirmed',
            field=models.BooleanField(default=False, verbose_name='Has agreed to terms and conditions'),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, help_text='Any other notes?', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='public_description',
            field=models.TextField(blank=True, help_text='Text that gets displayed to helpers.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='timeTaken',
            field=models.DurationField(blank=True, help_text='How long did it take to help?', null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='confident_online_comms',
            field=models.BooleanField(default=False, help_text='Is this person confident communicating online?'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='confident_online_shopping',
            field=models.BooleanField(default=False, help_text='Is this person confident online shopping?'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='internet_access',
            field=models.BooleanField(default=False, help_text='Does this person have internet access?'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='shielded',
            field=models.BooleanField(default=False, help_text='Is this person shielded?'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='smart_device',
            field=models.BooleanField(default=False, help_text='Does this person have a smart device?'),
        ),
    ]
