# Generated by Django 3.0.5 on 2020-04-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200426_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppreference',
            name='help_type',
        ),
        migrations.RemoveField(
            model_name='helppreference',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_query',
        ),
        migrations.DeleteModel(
            name='HelperWard',
        ),
        migrations.DeleteModel(
            name='HelpPreference',
        ),
    ]
