# Generated by Django 3.0.5 on 2020-04-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200428_1143'),
        ('core', '0014_auto_20200428_1321'),
    ]

    operations = [
    ]
