# Generated by Django 3.0.5 on 2020-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200428_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptype',
            name='private_description_template',
            field=models.TextField(help_text='Private description will be pre-filled with this text when picking this type of help for a Job', null=True),
        ),
        migrations.AddField(
            model_name='helptype',
            name='public_description_template',
            field=models.TextField(help_text='Public description will be pre-filled with this text when picking this type of help for a Job', null=True),
        ),
    ]
