# Generated by Django 3.0.5 on 2020-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200430_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helptype',
            name='private_description_template',
            field=models.TextField(blank=True, help_text='Private description will be pre-filled with this text when picking this type of help for a Job', null=True),
        ),
        migrations.AlterField(
            model_name='helptype',
            name='public_description_template',
            field=models.TextField(blank=True, help_text='Public description will be pre-filled with this text when picking this type of help for a Job', null=True),
        ),
    ]
