# Generated by Django 3.0.7 on 2020-11-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='daily_digest_optin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='weekly_digest_optin',
            field=models.BooleanField(default=False),
        ),
    ]
