# Generated by Django 3.0.7 on 2020-11-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201110_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_mon_morning', models.BooleanField(default=False, verbose_name='Monday morning')),
                ('available_mon_afternoon', models.BooleanField(default=False, verbose_name='Monday afternoon')),
                ('available_mon_evening', models.BooleanField(default=False, verbose_name='Monday evening')),
                ('available_tues_morning', models.BooleanField(default=False, verbose_name='Tuesday morning')),
                ('available_tues_afternoon', models.BooleanField(default=False, verbose_name='Tuesday afternoon')),
                ('available_tues_evening', models.BooleanField(default=False, verbose_name='Tuesday evening')),
                ('available_wed_morning', models.BooleanField(default=False, verbose_name='Wednesday morning')),
                ('available_wed_afternoon', models.BooleanField(default=False, verbose_name='Wednesday afternoon')),
                ('available_wed_evening', models.BooleanField(default=False, verbose_name='Wednesday evening')),
                ('available_thur_morning', models.BooleanField(default=False, verbose_name='Thursday morning')),
                ('available_thur_afternoon', models.BooleanField(default=False, verbose_name='Thursday afternoon')),
                ('available_thur_evening', models.BooleanField(default=False, verbose_name='Thursday evening')),
                ('available_fri_morning', models.BooleanField(default=False, verbose_name='Friday morning')),
                ('available_fri_afternoon', models.BooleanField(default=False, verbose_name='Friday afternoon')),
                ('available_fri_evening', models.BooleanField(default=False, verbose_name='Friday evening')),
                ('available_sat_morning', models.BooleanField(default=False, verbose_name='Saturday morning')),
                ('available_sat_afternoon', models.BooleanField(default=False, verbose_name='Saturday afternoon')),
                ('available_sat_evening', models.BooleanField(default=False, verbose_name='Saturday evening')),
                ('available_sun_morning', models.BooleanField(default=False, verbose_name='Sunday morning')),
                ('available_sun_afternoon', models.BooleanField(default=False, verbose_name='Sunday afternoon')),
                ('available_sun_evening', models.BooleanField(default=False, verbose_name='Sunday evening')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_fri_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_fri_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_fri_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_mon_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_mon_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_mon_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sat_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sat_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sat_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sun_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sun_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_sun_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_thur_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_thur_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_thur_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_tues_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_tues_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_tues_morning',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_wed_afternoon',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_wed_evening',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_wed_morning',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.VolunteerAvailability'),
        ),
    ]
