# Generated by Django 3.0.7 on 2021-03-11 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201110_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='data_consent_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
