# Generated by Django 3.0.5 on 2020-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_seed_requirement'),
        ('users', '0002_auto_20200512_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='help_types',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='categories.HelpType'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='categories.Requirement'),
        ),
    ]
