# Generated by Django 3.0.7 on 2021-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resident_data_consent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='data_consent_date',
            field=models.DateField(),
        ),
    ]
