# Generated by Django 3.0.5 on 2020-06-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email_secondary',
        ),
    ]
