# Generated by Django 3.0.5 on 2020-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='new_offer_help',
            field=models.BooleanField(default=False, verbose_name='Notifies the user of changes'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='new_ongoing',
            field=models.BooleanField(default=False, verbose_name='Notifies the user of changes'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='new_past',
            field=models.BooleanField(default=False, verbose_name='Notifies the user of changes'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='new_upcoming',
            field=models.BooleanField(default=False, verbose_name='Notifies the user of changes'),
        ),
    ]
