# Generated by Django 3.0.5 on 2020-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteer_external_volunteer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='time_given',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
