# Generated by Django 3.0.5 on 2020-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_volunteer_time_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='time_received',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
