# Generated by Django 3.0.7 on 2021-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210311_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='data_consent_date',
            field=models.DateField(help_text='When did this person give their consent to keeping their data in ToFro?\n                \n                <br><br>Before confirming, you must read the agreement to them and receive their explicit verbal consent. Otherwise, their data cannot be stored on this system.', verbose_name='Data agreement date'),
        ),
    ]
