# Generated by Django 3.0.5 on 2020-06-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_settings'),
        ('users', '0004_remove_person_email_secondary'),
    ]

    operations = [
    ]
