# Generated by Django 3.0.5 on 2020-05-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0002_seed'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='added_by',
            field=models.ForeignKey(help_text="What's your name?", on_delete=django.db.models.deletion.PROTECT, related_name='added_by', to='users.Coordinator'),
        ),
        migrations.AddField(
            model_name='action',
            name='coordinator',
            field=models.ForeignKey(help_text='Who will mediate this action?', on_delete=django.db.models.deletion.PROTECT, related_name='coordinator', to='users.Coordinator'),
        ),
        migrations.AddField(
            model_name='action',
            name='help_type',
            field=models.ForeignKey(help_text='Which kind of help is needed', null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.HelpType'),
        ),
        migrations.AddField(
            model_name='action',
            name='resident',
            field=models.ForeignKey(help_text='Who made the request?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Resident'),
        ),
        migrations.AddField(
            model_name='action',
            name='volunteer',
            field=models.ForeignKey(blank=True, help_text='Who will complete the action?', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Volunteer'),
        ),
    ]
