# Generated by Django 3.0.7 on 2020-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('icon_name', models.CharField(blank=True, help_text="Name of the fontawesome icon used to represent this type of help (among the 'free' ones: https://fontawesome.com/icons?d=gallery&m=free)", max_length=50, null=True)),
                ('private_description_template', models.TextField(blank=True, help_text='Private description will be pre-filled with this text when picking this type of help for a Action', null=True)),
                ('public_description_template', models.TextField(blank=True, help_text='Public description will be pre-filled with this text when picking this type of help for a Action', null=True)),
                ('requirements', models.ManyToManyField(blank=True, help_text='New actions with this help type will get these requirements by default. The requirements can then be adjusted per-action.', related_name='help_types', to='categories.Requirement', verbose_name='Default requirements')),
            ],
            options={
                'verbose_name': 'action type',
            },
        ),
    ]
