# Generated by Django 3.0.7 on 2021-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptype',
            name='maximum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='maximum number of volunteers required for action'),
        ),
        migrations.AddField(
            model_name='helptype',
            name='minimum_volunteers',
            field=models.SmallIntegerField(default=1, help_text='minimum number of volunteers required for action'),
        ),
    ]
