# Generated by Django 3.0.7 on 2021-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210318_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('icon_name', models.CharField(blank=True, help_text="Name of the fontawesome icon used to represent this type of referal (among the 'free' ones: https://fontawesome.com/icons?d=gallery&m=free)", max_length=50, null=True)),
            ],
        ),
    ]
