# Generated by Django 3.0.7 on 2021-05-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_referaltype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferalType',
            new_name='ReferralType',
        ),
    ]
