# Generated by Django 3.0.5 on 2020-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20200520_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptype',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='New actions with this help type will get these requirements by default. The requirements can then be adjusted per-action.', related_name='help_types', to='categories.Requirement', verbose_name='Default requirements'),
        ),
    ]
