# Generated by Django 3.0.5 on 2020-05-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_seed_helptype_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helptype',
            options={'verbose_name': 'action type'},
        ),
    ]
