# Generated by Django 3.0.7 on 2020-11-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20201122_2050'),
        ('actions', '0002_auto_20201122_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('requirements', models.ManyToManyField(to='coordinator_dashboard.ReferralRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_referral_id', models.CharField(blank=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('referral_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinator_dashboard.Organisation')),
                ('referral_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordinator_dashboard.ReferralType')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='referral_types',
            field=models.ManyToManyField(to='coordinator_dashboard.ReferralType'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('letter', 'Letter')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('communication_start_datetime', models.DateTimeField()),
                ('communication_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('actions', models.ManyToManyField(to='actions.ActionV2')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications_added', to='users.Person')),
                ('referrals', models.ManyToManyField(to='coordinator_dashboard.Referral')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='users.Resident')),
            ],
        ),
    ]
