# Generated by Django 3.0.5 on 2020-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(default=list, help_text='This field is updated automatically.', related_name='notificationrecipient', to='users.Person'),
        ),
    ]
