# Generated by Django 3.0.5 on 2020-05-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
