# Base Python3 image.
FROM python:3

# Install OS dependencies.
RUN apt-get update && apt-get install gdal-bin -y

# Set environment variables.
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Python requirements.
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the project files.
RUN mkdir /code
RUN mkdir /code/static
WORKDIR /code
COPY . /code

# Start a redis worker.
CMD python manage.py rqworker default
